apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: project-ns
spec:
  type: ClusterIP
  #type: NodePort
  selector:
    app/component: backend
  ports:
  - port: 8080
    targetPort: 8080
