apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-deployment
  namespace: project-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app/name: springboot
        app/component: backend
    spec:
      containers:
      - name: backend-container
        image: ravishankar90/project123-demo
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/test_ravi
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-cred
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-cred
              key: MYSQL_PASSWORD
