sonar.projectKey=Ravishankar9058_projectrepo
sonar.organization=ravishankar9058
sonar.sources=oled/src/main/java,frontend/frontend/src
sonar.tests=oled/src/test/java
sonar.java.binaries=oled/build/classes
