spring.datasource.url=jdbc:mysql://192.168.10.24:3306/test_ravi?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Admin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
