name: project-frontend-deployment
namespace: project-ns
replicas: 1
podLabels:
  app/name: frontend
  app/component: client
container:
  image: ravishankar90/project123-frontend
  ports:
    containerPort: 80

replicaCount: 1

image:
  repository: ravishankar90/project123-frontend
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false