apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  #type: NodePort
  selector:
    app/component: {{ .Values.podLabels.app/component }}
  ports:
  - port: {{ .Values.container.ports.containerPort }}
    targetPort: {{ .Values.container.ports.containerPort }}
