apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend-deployment
  namespace: project-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: client-container
      image: ravishankar90/project123-frontend
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
        - containerPort: 80
