server {
    listen 80;

    # Serve React app
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api requests to Spring Boot
    location /api/ {
        proxy_pass http://springboot-app:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
